stages:
  - test
  - lint

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  QT_QPA_PLATFORM: offscreen # Needed to run Qt Test offscreen apparently

cache:
  paths:
    - .cache/pip

test:
  stage: test
  image: python:3.11
  before_script:
  - apt-get update -qy
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  # Needed for Qt tests apparently as well
  - apt-get install -y libegl1 libxkbcommon0 libdbus-1-3 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-shape0 

  script:
    - pytest test/ --cov=src --cov-report=term
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  only:
    - branches

lint:
  stage: lint
  image: python:3.11
  before_script:
    - pip install --upgrade pip
    - pip install pylint PySide6
  script:
    - pylint src/
  allow_failure: true
  only:
    - branches