[tool.black]
line-length = 120
target-version = ['py310']

[tool.pylint.MASTER]
ignore = ["tests", "venv", ".git", "__pycache__"]
extension-pkg-allow-list = ["PySide6"] # Stop false positive import errors from Qt

[tool.pylint.TYPECHECK]
# Prevent false positives from Qt
generated-members = [
    "PySide6.*",
    ".*connect", 
]

[tool.pylint."MESSAGES CONTROL"]
# Without disabling these the score is 9.80/10 (Note: Qt fails on pylint, but these are false positives)
disable = [
            "C0301", 
            "C0103",
            "R0912", # (Too many branches) Collision logic is branch heavy, by splitting it it would I would have to pass too many arguments
            "R0914", # (Too many local variables) Physics computation require many variables
            "R0913", # (Too many arguments) Many hyperparameters for Agent
            "R0917",  # (Too many positional arguments) Standard for Machine Learning models 
            "R0902" # (Too many instan attributes) Standard for complex __init__ methods especially for games where there is a lot of states  
            ] 

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint.REPORTS]
output-format = "colorized"
reports = "no"

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["src"]
